//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Net;

// 
// This source code was auto-generated by wsdl, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="getSifarniciPortBinding", Namespace="http://zalihe.pa.ws/")]
public partial class getSifarnici : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback SifarniciOperationCompleted;
    
    /// <remarks/>
    public getSifarnici() {
        this.Url = "https://trust1.fzocg.net:443/wspaZalihe/getSifarnici";
    }

    /// <remarks/>
    public event SifarniciCompletedEventHandler SifarniciCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://zalihe.pa.ws/", ResponseNamespace="http://zalihe.pa.ws/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Sifarnici([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Ustanova, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Sifarnik, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Datum) {
        object[] results = this.Invoke("Sifarnici", new object[] {
                    Ustanova,
                    Sifarnik,
                    Datum});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSifarnici(string Ustanova, string Sifarnik, string Datum, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Sifarnici", new object[] {
                    Ustanova,
                    Sifarnik,
                    Datum}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndSifarnici(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void SifarniciAsync(string Ustanova, string Sifarnik, string Datum) {
        this.SifarniciAsync(Ustanova, Sifarnik, Datum, null);
    }
    
    /// <remarks/>
    public void SifarniciAsync(string Ustanova, string Sifarnik, string Datum, object userState) {
        if ((this.SifarniciOperationCompleted == null)) {
            this.SifarniciOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSifarniciOperationCompleted);
        }
        this.InvokeAsync("Sifarnici", new object[] {
                    Ustanova,
                    Sifarnik,
                    Datum}, this.SifarniciOperationCompleted, userState);
    }
    
    private void OnSifarniciOperationCompleted(object arg) {
        if ((this.SifarniciCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SifarniciCompleted(this, new SifarniciCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void SifarniciCompletedEventHandler(object sender, SifarniciCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SifarniciCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal SifarniciCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}
